### ISSUE TITLE
Migrate ‘android’ directory from ‘Revolutionary_Farmers’ to ‘Revo-Android’ preserving commit history

### ISSUE THREAD

**Issue by sasasamaes** [Crypto-Jaguars/Revo-Android#1]
The goal is to extract the frontend component from our existing monorepo and migrate it to the newly created revo-frontend repository while preserving the entire git history specific to the frontend directory. We will use git subtree split to create a clean extraction of the frontend codebase, ensuring all commit history, branches, and relevant metadata are transferred accurately. This migration will improve our project's modularity, allow independent versioning of the frontend, and potentially simplify our development workflow by providing a dedicated repository for frontend-specific tasks and contributions.

See more details here:
https://docs.github.com/es/get-started/using-git/splitting-a-subfolder-out-into-a-new-repository

**Comment by mimisavage** [comment]
Can I take this issue?

**Comment by Supa-mega** [comment]
May I take this issue on?

**Comment by chigozzdevv** [comment]
Could I grab this task?

**Comment by kayceeDev** [comment]
I’d like to help with this.

**Comment by RajeshRk18** [comment]
I will take up this issue. I will use git subtree split command to move android directory from ‘Revolutionary_Farmers’ to ‘Revo-Android’. As someone who has handled this kind of migration before, I can get it done smoothly!

**Comment by ShantelPeters** [comment]
Mind if I take this issue?

**Comment by Jagadeeshftw** [comment]
Hi, I’d love to work on this issue as I have strong experience with both Stellar and Rust. I’ve developed secure and efficient smart contracts, blockchain integrations, and high-performance backend systems. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by sajalbnl** [comment]
Let me handle this issue!

**Comment by pablomadrigal** [comment]
## I'm Pablo Madrigal.
I'm a Fullstack Developer with more than 5 years of experience primary on React and Node.js and now learning web3, I'm also part of Dojo Coding ⛩️

I have migrate mono-repos to multiple single repos in the past, one of the biggest was extracting the components from an application to create it's own components library and reuse it on multiple micro FE

## Problem
Migrate ‘android’ directory from ‘Revolutionary_Farmers’ to ‘Revo-Android’

## Solution
I'm going to create a new Repo from a web subfolder folowing the instructions on [Github](https://docs.github.com/es/get-started/using-git/splitting-a-subfolder-out-into-a-new-repository "Github")

**Comment by xJeffx23** [comment]
Hello Revolutionary Farmers,

# My background

I'm Jefferson, a software engineer and part of the Dojo Coding community, and I'd like to contribute to this issue. I have no previous experience in this area but I am willing to do my best to complete this issue.

# How I plan to solve this problem
To resolve this issue, I will perform the following steps:
1.I will dig more into the github documentation related to this issue.
2.I will start testing on what is requested in the issue.
3.Verify that everything implemented is ok.
4.Make a pr and wait for feedback.

**Comment by Kom02** [comment]
Hi, I’m Kevin Obando, a full-stack software developer with 2 years of experience. Currently, I’m exploring the world of blockchain and am eager to gain hands-on experience in this field.

**Comment by DuendexCR** [comment]
Would love to tackle this!
